CREATE TABLE IF NOT EXISTS color_lookup (
colorID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
        colorHex INT(15) DEFAULT NULL,
        colorDesc NVARCHAR(30) DEFAULT NULL
        
        
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;