CREATE TABLE IF NOT EXISTS category_lookup (
categoryID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
        categoryType NVARCHAR(50) DEFAULT NULL
        
        
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
